# Generated by Django 2.1.5 on 2021-05-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/images/Koala.jpg', upload_to=''),
        ),
    ]
