# Generated by Django 2.1.5 on 2021-05-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0003_auto_20210530_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/images/Koala.jpg/', null=True, upload_to=''),
        ),
    ]
