# Generated by Django 2.1.5 on 2021-05-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0004_auto_20210530_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='profile_pic',
            field=models.ImageField(blank=True, default='Koala.jpg/', null=True, upload_to=''),
        ),
    ]
