# Generated by Django 2.1.5 on 2021-06-01 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0008_auto_20210530_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='profile_pic',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='products',
            name='tag',
        ),
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Beauty', 'Beauty')], default='TAGS[0]', max_length=200),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
